-- Seed 28 OPD (REQ-01) — idempoten: aman dijalankan ulang tanpa duplikat
INSERT INTO master_opd (nama_opd, singkatan, is_active) VALUES ('Dinas Pendidikan dan Kebudayaan', NULL, TRUE) ON CONFLICT (nama_opd) DO NOTHING;
INSERT INTO master_opd (nama_opd, singkatan, is_active) VALUES ('Dinas Kesehatan', NULL, TRUE) ON CONFLICT (nama_opd) DO NOTHING;
INSERT INTO master_opd (nama_opd, singkatan, is_active) VALUES ('Dinas Pekerjaan Umum dan Penataan Ruang', NULL, TRUE) ON CONFLICT (nama_opd) DO NOTHING;
INSERT INTO master_opd (nama_opd, singkatan, is_active) VALUES ('Dinas Perumahan dan Kawasan Permukiman', NULL, TRUE) ON CONFLICT (nama_opd) DO NOTHING;
INSERT INTO master_opd (nama_opd, singkatan, is_active) VALUES ('Satuan Polisi Pamong Praja', NULL, TRUE) ON CONFLICT (nama_opd) DO NOTHING;
INSERT INTO master_opd (nama_opd, singkatan, is_active) VALUES ('Badan Penanggulangan Bencana Daerah', NULL, TRUE) ON CONFLICT (nama_opd) DO NOTHING;
INSERT INTO master_opd (nama_opd, singkatan, is_active) VALUES ('Dinas Sosial', NULL, TRUE) ON CONFLICT (nama_opd) DO NOTHING;
INSERT INTO master_opd (nama_opd, singkatan, is_active) VALUES ('Dinas Tenaga Kerja', NULL, TRUE) ON CONFLICT (nama_opd) DO NOTHING;
INSERT INTO master_opd (nama_opd, singkatan, is_active) VALUES ('Dinas Lingkungan Hidup', NULL, TRUE) ON CONFLICT (nama_opd) DO NOTHING;
INSERT INTO master_opd (nama_opd, singkatan, is_active) VALUES ('Dinas Kependudukan dan Pencatatan Sipil', NULL, TRUE) ON CONFLICT (nama_opd) DO NOTHING;
INSERT INTO master_opd (nama_opd, singkatan, is_active) VALUES ('Dinas Pemberdayaan Masyarakat, Perempuan, Perlindungan Anak, Pengendalian Penduduk dan Keluarga Berencana', NULL, TRUE) ON CONFLICT (nama_opd) DO NOTHING;
INSERT INTO master_opd (nama_opd, singkatan, is_active) VALUES ('Dinas Perhubungan', NULL, TRUE) ON CONFLICT (nama_opd) DO NOTHING;
INSERT INTO master_opd (nama_opd, singkatan, is_active) VALUES ('Dinas Komunikasi, Informatika, dan Statistik', NULL, TRUE) ON CONFLICT (nama_opd) DO NOTHING;
INSERT INTO master_opd (nama_opd, singkatan, is_active) VALUES ('Dinas Penanaman Modal dan Pelayanan Terpadu Satu Pintu', NULL, TRUE) ON CONFLICT (nama_opd) DO NOTHING;
INSERT INTO master_opd (nama_opd, singkatan, is_active) VALUES ('Dinas Kepemudaan, Olahraga, dan Pariwisata', NULL, TRUE) ON CONFLICT (nama_opd) DO NOTHING;
INSERT INTO master_opd (nama_opd, singkatan, is_active) VALUES ('Dinas Perpustakaan dan Kearsipan', NULL, TRUE) ON CONFLICT (nama_opd) DO NOTHING;
INSERT INTO master_opd (nama_opd, singkatan, is_active) VALUES ('Dinas Pertanian dan Pangan', NULL, TRUE) ON CONFLICT (nama_opd) DO NOTHING;
INSERT INTO master_opd (nama_opd, singkatan, is_active) VALUES ('Dinas Perdagangan Perindustrian Koperasi dan Usaha Mikro', NULL, TRUE) ON CONFLICT (nama_opd) DO NOTHING;
INSERT INTO master_opd (nama_opd, singkatan, is_active) VALUES ('Sekretariat Daerah', NULL, TRUE) ON CONFLICT (nama_opd) DO NOTHING;
INSERT INTO master_opd (nama_opd, singkatan, is_active) VALUES ('Sekretariat Dewan Perwakilan Rakyat Daerah', NULL, TRUE) ON CONFLICT (nama_opd) DO NOTHING;
INSERT INTO master_opd (nama_opd, singkatan, is_active) VALUES ('Badan Perencanaan Pembangunan, Riset dan Inovasi Daerah', NULL, TRUE) ON CONFLICT (nama_opd) DO NOTHING;
INSERT INTO master_opd (nama_opd, singkatan, is_active) VALUES ('Badan Pengelola Keuangan dan Aset Daerah', NULL, TRUE) ON CONFLICT (nama_opd) DO NOTHING;
INSERT INTO master_opd (nama_opd, singkatan, is_active) VALUES ('Badan Kepegawaian dan Pengembangan Sumber Daya Manusia', NULL, TRUE) ON CONFLICT (nama_opd) DO NOTHING;
INSERT INTO master_opd (nama_opd, singkatan, is_active) VALUES ('Inspektorat Daerah', NULL, TRUE) ON CONFLICT (nama_opd) DO NOTHING;
INSERT INTO master_opd (nama_opd, singkatan, is_active) VALUES ('Kecamatan Magelang Selatan', NULL, TRUE) ON CONFLICT (nama_opd) DO NOTHING;
INSERT INTO master_opd (nama_opd, singkatan, is_active) VALUES ('Kecamatan Magelang Tengah', NULL, TRUE) ON CONFLICT (nama_opd) DO NOTHING;
INSERT INTO master_opd (nama_opd, singkatan, is_active) VALUES ('Kecamatan Magelang Utara', NULL, TRUE) ON CONFLICT (nama_opd) DO NOTHING;
INSERT INTO master_opd (nama_opd, singkatan, is_active) VALUES ('Badan Kesatuan Bangsa dan Politik', NULL, TRUE) ON CONFLICT (nama_opd) DO NOTHING;
